[package]
name = "jwt_nbf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "9.0.0"
serde = {version = "1.0", features = ["derive"] }
rocket = "0.5.0-rc.2"