[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.3"
aws-sdk-s3 = "0.35.0"
aws-sdk-s3control = "0.35.0"

aws-config = "0.57.1"
tokio = { version = "1.33.0", features = ["full"] }
