[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
tokio = { version = "1.33.0", features = ["full"] }
tokio-postgres = "0.7.10"
[dependencies.rocket_db_pools]
version = "0.1.0"
features = ["deadpool_postgres", "deadpool_redis"]