[package]
name = "rollback"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
dotenvy = "0.15"


[dependencies.sqlx]
version = "0.7.4"
default-features = false
features = ["macros", "migrate", "runtime-tokio-rustls", "mysql", "postgres"]
